"""Abstract base class for editor-file generators (CLAUDE.md, cursor.md, etc.).

Handles the marker-based merge strategy so subclasses only need to define
the filename, marker tag, template name, and user placeholder text.

Merge rules:
  - No existing file      → create with placeholder + Repowise section
  - File without markers  → append Repowise section at bottom
  - File with markers     → replace ONLY content between markers
"""

from __future__ import annotations

import re
from abc import ABC, abstractmethod
from pathlib import Path

import jinja2

from repowise.core.fsutils import atomic_write_text

from .data import EditorFileData


class BaseEditorFileGenerator(ABC):
    """Base class for generating and maintaining editor configuration files."""

    #: Format strings for the HTML comment markers. {tag} is replaced by marker_tag.
    MARKER_START_FMT = (
        "<!-- {tag}:START — Do not edit below this line. Auto-generated by Repowise. -->"
    )
    MARKER_END_FMT = "<!-- {tag}:END -->"

    def __init__(self) -> None:
        templates_dir = Path(__file__).resolve().parent.parent / "templates"
        self._jinja_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(templates_dir)),
            undefined=jinja2.StrictUndefined,
            keep_trailing_newline=True,
            trim_blocks=True,
            lstrip_blocks=True,
        )

    # ------------------------------------------------------------------
    # Abstract interface — subclasses define these
    # ------------------------------------------------------------------

    @property
    @abstractmethod
    def filename(self) -> str:
        """Output filename, e.g. 'CLAUDE.md'."""

    @property
    @abstractmethod
    def marker_tag(self) -> str:
        """Marker tag prefix, e.g. 'REPOWISE'. Used in START/END comments."""

    @property
    @abstractmethod
    def template_name(self) -> str:
        """Jinja2 template file name, e.g. 'claude_md.j2'."""

    @property
    @abstractmethod
    def user_placeholder(self) -> str:
        """Content written above the Repowise section when creating a new file."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def render(self, data: EditorFileData) -> str:
        """Render just the managed section content (without markers)."""
        template = self._jinja_env.get_template(self.template_name)
        return template.render(data=data)

    def write(self, repo_path: Path, data: EditorFileData) -> Path:
        """Write the file to *repo_path*, preserving user content outside markers.

        Returns the path of the written file.
        """
        target = repo_path / self.filename
        marker_start = self.MARKER_START_FMT.format(tag=self.marker_tag)
        marker_end = self.MARKER_END_FMT.format(tag=self.marker_tag)

        managed = self.render(data)
        wrapped = f"{marker_start}\n{managed}\n{marker_end}"

        if not target.exists():
            content = f"{self.user_placeholder}\n{wrapped}\n"
        else:
            existing = target.read_text(encoding="utf-8")
            if marker_start in existing:
                # Replace the managed section in-place
                pattern = re.escape(marker_start) + r".*?" + re.escape(marker_end)
                content = re.sub(pattern, wrapped, existing, flags=re.DOTALL)
            else:
                # Append managed section; preserve all existing content
                content = existing.rstrip() + "\n\n" + wrapped + "\n"

        atomic_write_text(target, content, newline="\n")
        return target

    def render_full(self, repo_path: Path, data: EditorFileData) -> str:
        """Return what the full file would look like without writing to disk."""
        marker_start = self.MARKER_START_FMT.format(tag=self.marker_tag)
        marker_end = self.MARKER_END_FMT.format(tag=self.marker_tag)
        managed = self.render(data)
        wrapped = f"{marker_start}\n{managed}\n{marker_end}"
        target = repo_path / self.filename
        if not target.exists():
            return f"{self.user_placeholder}\n{wrapped}\n"
        existing = target.read_text(encoding="utf-8")
        if marker_start in existing:
            pattern = re.escape(marker_start) + r".*?" + re.escape(marker_end)
            return re.sub(pattern, wrapped, existing, flags=re.DOTALL)
        return existing.rstrip() + "\n\n" + wrapped + "\n"
