"""Mock provider for testing — returns fixture responses without any API calls.

MockProvider is the only provider used in repowise's test suite. It fully
implements BaseProvider so tests exercise the real interface without consuming
API tokens or requiring network access.

Usage in tests:
    # Simple: default inline response
    provider = MockProvider()
    response = await provider.generate("sys", "user")

    # Fixture-based: load from tests/providers/fixtures/<name>.json
    provider = MockProvider(fixture_name="file_page_response")

    # Preset: control exact responses per call
    provider = MockProvider(responses=[
        GeneratedResponse("First page", 100, 50),
        GeneratedResponse("Second page", 200, 80),
    ])
    r1 = await provider.generate("sys", "user")  # "First page"
    r2 = await provider.generate("sys", "user")  # "Second page"
    r3 = await provider.generate("sys", "user")  # "Second page" (last repeated)

    # Assertions
    assert provider.call_count == 3
    assert provider.calls[0]["user_prompt"] == "user"
"""

from __future__ import annotations

import json
from pathlib import Path

from repowise.core.providers.llm.base import BaseProvider, GeneratedResponse
from repowise.core.reasoning import ReasoningMode

# Resolve fixture directory relative to this file so tests work regardless
# of working directory. Goes up: mock.py → providers/ → core/ → repowise/ →
# src/ → packages/core/ → (repo root) → tests/providers/fixtures/
_FIXTURE_DIR = (
    Path(__file__).parent  # providers/
    .parent                # core/
    .parent                # repowise/
    .parent                # src/
    .parent                # packages/core/
    .parent                # packages/
    .parent                # repo root
    / "tests"
    / "providers"
    / "fixtures"
)

_DEFAULT_CONTENT = """\
## Overview

This is a mock documentation page generated by repowise's MockProvider.

### Purpose

This module provides core functionality for the sample repository.

### Public API

See the source file for the full symbol list.
"""


class MockProvider(BaseProvider):
    """Deterministic test provider — no network calls, no API keys.

    Call history is recorded and accessible via `call_count` and `calls`
    for assertion in tests. Use `reset()` between test cases when reusing
    the same instance.

    Args:
        fixture_name: Name of a JSON fixture file (without .json).
                      Loaded from tests/providers/fixtures/{name}.json.
                      Falls back to the inline default if file not found.
        model:        Model name returned by model_name property.
        responses:    Optional preset list of GeneratedResponse objects.
                      Returned in order; the last response repeats indefinitely.
                      When provided, overrides fixture_name.
    """

    def __init__(
        self,
        fixture_name: str = "default",
        model: str = "mock-model-1",
        responses: list[GeneratedResponse] | None = None,
    ) -> None:
        self._fixture_name = fixture_name
        self._model = model
        self._preset_responses = responses or []
        self._call_count = 0
        self._calls: list[dict[str, object]] = []

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str:
        return self._model

    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_tokens: int = 4096,
        temperature: float = 0.3,
        request_id: str | None = None,
        reasoning: ReasoningMode = "auto",
        cache_hints: tuple = (),
    ) -> GeneratedResponse:
        """Return a fixture response without calling any external API."""
        self._calls.append(
            {
                "system_prompt": system_prompt,
                "user_prompt": user_prompt,
                "max_tokens": max_tokens,
                "temperature": temperature,
                "request_id": request_id,
                "reasoning": reasoning,
            }
        )
        call_idx = self._call_count
        self._call_count += 1

        # Preset responses take priority
        if self._preset_responses:
            idx = min(call_idx, len(self._preset_responses) - 1)
            return self._preset_responses[idx]

        # Try loading from fixture file
        fixture_path = _FIXTURE_DIR / f"{self._fixture_name}.json"
        if fixture_path.exists():
            data = json.loads(fixture_path.read_text(encoding="utf-8"))
            return GeneratedResponse(**data)

        # Default inline response
        return GeneratedResponse(
            content=f"{_DEFAULT_CONTENT}\n\n---\n*Mock call #{call_idx + 1}*",
            input_tokens=150,
            output_tokens=75,
            cached_tokens=0,
            usage={"mock": True, "fixture": self._fixture_name, "call": call_idx},
        )

    @property
    def call_count(self) -> int:
        """Number of times generate() has been called on this instance."""
        return self._call_count

    @property
    def calls(self) -> list[dict[str, object]]:
        """Ordered list of all recorded generate() call arguments."""
        return list(self._calls)

    def reset(self) -> None:
        """Reset call history. Useful when reusing a provider across test cases."""
        self._call_count = 0
        self._calls.clear()
